#!/bin/bash
function run {
  base=$(basename $1})
  pref=${base%.*};

  rm outputs/$pref.* > /dev/null 2>&1;

  # # call golite with command and filename
  ./src/golite $2 $1  1> /dev/null;
  # # Only write if successful
  if [ "$?" -eq 0 ]; then
    ./src/golite $2 $1 1> "outputs/$pref.$3";
  fi
}

if [ "$#" -eq 0 ]; then
  make -C src/
else
  # assumes the script was called like one of the following:
  #   a) ./run file [-pptype | -dumpsymtab] ---> golite flag file
  #   b) ./run file                         ---> golite pretty

  p="$1"
  case $p in
    -h|--help)
      echo "./run [-h|-v|-dumpsymtab|-pptype] filename"
      exit
      ;;
    -v|--version)
      echo "version 4"
      exit
      ;;
    -dumpsymtab)
      run $2 "dumpsymtab" "symtab"
      ;;
    -pptype)
      run $2 "pptype" "pptype.go"
      ;;
    *)    #unknown option - assume it's filename
      run $p "code" "cpp"
      ;;
  esac
fi
