#!/bin/bash
function run {
  # # call golite with command and filename
  ./src/golite $2 $1  1> /dev/null;
  # # Only write if successful
  if [ "$?" -eq 0 ]; then
    ./src/golite $2 $1 1> "outputs/$pref.$3";
  else
    exit
  fi
}

if [ "$#" -eq 0 ]; then
  make -C src/
else
  # find filename
  for last; do true; done

  code=true

  base=$(basename $last})
  pref=${base%.*};
  rm outputs/$pref.* > /dev/null 2>&1;

  while [[ $# > 0 ]]
  do
    p="$1"
    case $p in
      -h|--help)
        echo "./run [-h|-v|-pretty|-dumpsymtab|-pptype|-code] filename"
        echo "if no flag is given, will generate all files to output/"
        exit
        ;;
      -v|--version)
        echo "version 4"
        exit
        ;;
      -pretty)
        code="false"
        run $last "pretty" "pretty.go"
        ;;
      -dumpsymtab)
        code="false"
        run $last "dumpsymtab" "symtab"
        ;;
      -pptype)
        code="false"
        run  $last "pptype" "pptype.go"
        ;;
      -code)
        code="false"
        run $last "code" "cpp"
        ;;
      *)    #unknown option / incorrectly assumes that there was nothing and create all files
        if [ "$code" = true ]; then
          run $last "pretty" "pretty.go"
          run $last "dumpsymtab" "symtab"
          run $last "pptype" "pptype.go"
          run $last "code" "cpp"
        fi
        ;;
    esac
    shift
  done
fi
